#!/usr/bin/env python3
import argparse
import os
import signal

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk  # noqa: E402

parser = argparse.ArgumentParser()
parser.add_argument("--host", required=True)
parser.add_argument(
    "--image", default="ghcr.io/fabianonunes/openfortivpn.saml.docker:0.5.0"
)
args, mass = parser.parse_known_args()


class Browser:
    window = None
    terminal = None

    def run(self):
        Gtk.init(None)
        self.window = Gtk.Window(title="VPN", icon_name="network-vpn")
        self.window.connect("delete-event", self.quit)
        self.window.resize(500, 570)
        self.window.add(self.build_vte())
        self.window.show_all()
        self.terminal.grab_focus()
        return self

    def build_cmd(self):
        priv = "env" if os.access("/var/run/docker.sock", os.W_OK | os.R_OK) else "sudo"
        return [
            f"/usr/bin/{priv}",
            "docker",
            "run",
            "--init",
            "--rm",
            "--network=host",
            "--device=/dev/ppp",
            "--cap-drop=ALL",
            "--cap-add=DAC_OVERRIDE",
            "--cap-add=NET_ADMIN",
            "--volume",
            "/etc/resolv.conf:/etc/resolv.conf",
            "--tty",
            "--interactive",
            args.image,
            args.host,
            "--saml-login",
            *mass,
        ]

    def quit(self, _a=None, _b=None):
        try:
            self.stop_container()
            self.window.destroy()
            Gtk.main_quit()
            while Gtk.events_pending():
                Gtk.main_iteration()
        except Exception as err:
            print(err)
            exit(1)

    def stop_container(self, _a=None, _b=None):
        if self.terminal:
            # o openfortivpn não reage ao SIGHUP propagado pelo Vte ao sair
            self.terminal.feed_child(b"\x03")  # CTRL+C

    def build_vte(self):
        gi.require_version("Vte", "2.91")
        from gi.repository import Vte

        self.terminal = Vte.Terminal()

        saml_url = f"https://{args.host}/remote/saml/start?redirect=1"
        self._saml_opened = False

        def on_contents_changed(widget):
            if self._saml_opened:
                return
            try:
                text = widget.get_text_format(Vte.Format.TEXT)
            except AttributeError:
                result = widget.get_text(None)
                text = result[0]
            if text and "Listening for SAML" in text:
                self._saml_opened = True
                Gtk.show_uri_on_window(self.window, saml_url, 0)

        self.terminal.connect("contents-changed", on_contents_changed)
        self.terminal.spawn_async(
            Vte.PtyFlags.DEFAULT,  # pty_flags
            os.environ["HOME"],  # working_directory
            self.build_cmd(),  # argv
            [],  # envv
            0,  # spawn_flags: GLib.SpawnFlags.DEFAULT
            None,  # child_setup
            None,  # child_setup_data - não documentado
            -1,  # timeout
        )

        scroller = Gtk.ScrolledWindow()
        scroller.add(self.terminal)
        return scroller


if __name__ == "__main__":
    b = Browser().run()
    signal.signal(signal.SIGINT, b.quit)
    Gtk.main()
